version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "dillanTrussle"
    default_labels:
      - "dependabot"
    version_requirement_updates: "increase_versions"